parameters:
#    xsolve_unit_skelgen.example.class: Xsolve\UnitSkelgenBundle\Example

services:
#    xsolve_unit_skelgen.example:
#        class: %xsolve_unit_skelgen.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
