parameters:
    xsolve_unit_skelgen.class_locator.class: Xsolve\UnitSkelgenBundle\Utils\ClassLocator

services:
    xsolve_unit_skelgen.class_locator:
        class: %xsolve_unit_skelgen.class_locator.class%
        calls:
          - [setContainer, ['@service_container']]
