parameters:
    xsolve_unit_skelgen.class_locator.class: Xsolve\UnitSkelgenBundle\Utils\ClassLocator
    xsolve_unit_skelgen.class_runner: Xsolve\UnitSkelgenBundle\Utils\ClassRunner
    xsolve_unit_skelgen.test_runner: Xsolve\UnitSkelgenBundle\Utils\TestRunner
    xsolve_unit_skelgen.name_tools: Xsolve\UnitSkelgenBundle\Utils\NameTools

services:
  
    xsolve_unit_skelgen.class_locator:
        class: %xsolve_unit_skelgen.class_locator.class%
        arguments:
            - "@service_container"
          
    xsolve_unit_skelgen.class_runner:
        class: %xsolve_unit_skelgen.class_runner%
        arguments:
            - "@service_container"
        
    xsolve_unit_skelgen.test_runner:
        class: %xsolve_unit_skelgen.test_runner%
        arguments:
            - "@service_container"
          
    xsolve_unit_skelgen.name_tools:
        class: %xsolve_unit_skelgen.name_tools%
        arguments:
            - "@service_container"
