parameters:
    xsolve_unit_skelgen.class_locator.class: Xsolve\UnitSkelgenBundle\Utils\ClassLocator
    xsolve_unit_skelgen.runner: Xsolve\UnitSkelgenBundle\Utils\Runner

services:
  
    xsolve_unit_skelgen.class_locator:
        class: %xsolve_unit_skelgen.class_locator.class%
        calls:
          - [setContainer, ["@service_container"]]
          
    xsolve_unit_skelgen.runner:
        class: %xsolve_unit_skelgen.runner%
