language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --dev --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml Tests/

after_script:
  - php vendor/bin/coveralls
